### ISSUE TITLE
Using Universal Module Define(UMD)

### ISSUE THREAD

**Issue by hg-pyun** [devjiro76/coolsole#3]
The current project uses the `isNode()` method to distinguish between the browser and the node environment. [UMD](https://github.com/umdjs/umd) makes it easier to support AMD, Commonjs, and nodejs environments.

Also, if you do not have a project that requires bundling, it is more efficient to use only babel.

**Comment by devjiro76** [comment]
thanks a lot feedback :)

**Comment by devjiro76** [comment]
[Close] 
1. Using UMD - done
2. Remove isNode() methonde - done 

Thanks for your feedback.
If there is anything more, don't be hesitated please.

**Comment by hg-pyun** [comment]
@devjiro76 
And [Babel has UMD plugins](https://www.google.co.kr/search?q=babel+umd&oq=babel+umd&aqs=chrome..69i57j69i60l3j69i59l2.1279j0j7&sourceid=chrome&ie=UTF-8) performance is good. I suggest that.

**Comment by devjiro76** [comment]
@hg-pyun 

Yeah, I tried to do with ["babel-plugin-transform-es2015-modules-umd"](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-umd)  
But it works strangely so I referred UMD template. (Maybe I made wrong config file)

And do you know how can generate & assign library globally as like jQuery?

When we import jQuery with <script src="./jQuery.js"/>
As you know the '$' variable is assigend to global. 
I want to do same thing with this library.

I expected this line `global.coolsole = factory(global.cool);`  will work for that, but it was not.

**Comment by devjiro76** [comment]
@hg-pyun 

PS.
I wrote to something to ask about create global library as like as jQuery ('$' is assigned window.$)
but I found solution so delete the comment.

1. Thanks for your info.
And I tried to do with it (plugin-es6-to-umd) but it works very strangely and not worked properly.
So I referred document which you suggest above. thanks.
